### ISSUE TITLE
Ideas for dynamic status udpate?

### ISSUE THREAD

**Issue by rzsombor** [ghoranyi/ismetroline3onfire#3]
As far as I can tell the status needs manual updates - you guys have some ideas on making this automated?

**Comment by ghoranyi** [comment]
It's almost done. Luckily bkkinfo.hu has a wonderful API which you can just poll to see if there is bus replacement on M3.

**Comment by nagyadam2092** [comment]
@ghoranyi well that's not a 100% proof; e.g. last time they had to use replacement buses because someone fell under the metro - no fire included

**Comment by ghoranyi** [comment]
True that. Do you have a better idea? My plan is to collect some stats on bkkinfo. They have pretty verbose events, something like this:
```
$ curl -s http://www.bkk.hu/apps/bkkinfo/lista-api.php | jq '.active[] | select(.jaratokByFajta[].type == "metro" and .jaratokByFajta[].jaratok[] == "M2")'
{
  "id": "31153",
  "vege": null,
  "kezd": {
    "epoch": "1480719600",
    "exact": false,
    "active": true,
    "ev": "2016",
    "honap": "december",
    "nap": " 3",
    "napnev": "szombat",
    "Pnapnev": "szombat",
    "ido": "00:00"
  },
  "modositva": {
    "epoch": 1483868849,
    "datum": "2017-01-08 10:47:29"
  },
  "opcio": {
    "zavar_ok": "epitkezes",
    "szabad_szoveg": "A D2-es átkelőhajó a Kossuth Lajos tér és a Batthyány tér között nem közlekedik jegesedés miatt.",
    "zavar_tip": "mkihagy",
    "zavar_megallo": "0;F00958",
    "potbusz": "1"
  },
  "osszSzoveg": "2016. december 03., szombat üzemkezdettől - visszavonásig",
  "kezdSzoveg": "2016. december 03., szombat üzemkezdettől",
  "vegeSzoveg": "visszavonásig",
  "active": true,
  "jaratokByFajta": [
    {
      "type": "metro",
      "jaratok": [
        "M2"
      ]
    }
  ],
  "elnevezes": "autóbuszos pótlás, megálló kihagyás (építkezés)"
```
I hope if we see some events, we can find a pattern.

**Comment by nagyadam2092** [comment]
Maybe using a RegExp at "elnevezes" to find certain words like `/(égő|kigyulladt|tűz)/g`

**Comment by ghoranyi** [comment]
I've create a cronjob like this:
```
*/5 * * * * curl --silent http://www.bkk.hu/apps/bkkinfo/lista-api.php | jq -c '.active[]' | while read i; do id=$(echo "$i" | jq -r '.id'); curl -XPUT https://search-metro3onfire-p7eavs2kfepqn25tkkjg3rgh4i.eu-cenral-1.es.amazonaws.com/bkk_info_events/event/$id -d "$i"; done > /dev/null
```
The endpoint is an Elasticsearch instance in AWS. This will be perfect for finding the pattern.
Currently the ES is not accessible for the world. I don't yet know how can expose it in a safe way.

**Comment by kbence** [comment]
@nagyadam2092 as far as I've noticed, they never put the _real_ reason if it's on fire. They only say "műszaki ok" or something like that. But that's probably enough for us now :). @ghoranyi: we should store some history of that file so we won't miss the next one.

**Comment by ghoranyi** [comment]
@kbence That's why it sends it to an Elasticsearch node ;) From now on we will have all events there from this endpoint over there.

**Comment by ghoranyi** [comment]
Now we just need a 🔥 to see how does it look like.

**Comment by rzsombor** [comment]
Thanks, looks like we have an v1 solution here so I'm closing this issue for now!
