### ISSUE TITLE
Secrets

### ISSUE THREAD

**Issue by lintaba** [ghoranyi/ismetroline3onfire#4]
Are the secrets intentionally put publicly on config files? (s3, slack)

**Comment by ghoranyi** [comment]
Thanks for raising the attention. You mean these? https://github.com/ghoranyi/ismetroline3onfire/blob/master/.travis.yml#L7

**Comment by ghoranyi** [comment]
Those secrets are actually encrypted secrets added to the `.yml` file with the `travis encrypt` command, based on https://docs.travis-ci.com/user/encryption-keys/.
I believe it is ok that it is public since only Travis can decrypt them.
